name: CI/CD
on:
  push:
    branches: [ master ]
jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      doc: ${{ steps.filter.outputs.doc }}
      not-doc: ${{ steps.filter.outputs.not-doc }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.2.1
      id: filter
      with:
        filters: |
          doc:
            - '**/*.md'
          not-doc:
            - '**/!(*.md)'
